// lib/services/language_service.dart
import 'package:flutter/material.dart';

class LanguageService {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'language': 'Language',
      'save': 'Save',
      'welcome': 'Welcome',
      'Change Password': 'Change Password',
      'Current Password': 'Current Password',
      'New Password': 'New Password',
      'Confirm New Password': 'Confirm New Password',
      'MTG-text': 'Migrate to Google authentication for easier sign-in',
      'Disconnect Google': 'Disconnect Google',
      'Migrate to Google': 'Migrate to Google',
      'Settings': 'Settings',
      'Click the first point to close shape and save it':
          'Click the first point to close shape and save it',
      'Enter Environmental Parameters': 'Enter Environmental Parameters',
      'Predict': 'Predict',
      'Select Model': 'Select Model',
      'Select Crop': 'Select Crop',
      'Check Suitability': 'Check Suitability',
      'Sectors': 'Sectors',
      'Yields': 'Yields',
      'Edit Product': 'Edit Product',
      'Save Profile': 'Save Profile',
      'Edit Profile': 'Edit Profile',
      'Record Details': 'Record Details',
      'Product Information': 'Product Information',
      'Farmer Name': 'Farmer Name',
      'Farm Name': 'Farm Name',
      'Location': 'Location',
      'Farm Information': 'Farm Information',
      "Yield Information": "Yield Information",
      'Area harvested (Ha)': 'Area harvested (Ha)',
      'Yield Amount': 'Yield Amount',
      'Harvest Date': 'Harvest Date',
      'Value in (Php)': 'Value in (Php)',
      'Documentation': 'Documentation',
      'Additional Information': 'Additional Information',
      'Notes': 'Notes',
      'Delete Yield': 'Delete Yield',
      'Are you sure you want to delete this record?':
          'Are you sure you want to delete this record?',
      'Cancel': 'Cancel',
      'Delete': 'Delete',
      'Product Sector': 'Product Sector',
      'Product Name': 'Product Name',
      'Farms': 'Farms',
      'Add Record': 'Add Record',
      'Adding...': 'Adding...',
      'Farm Profile': 'Farm Profile',
      'Recent Records': ' Recent Records',
      'Products & Distribution': 'Products & Distribution',
      'Create Farm': 'Create Farm',
      'Create New Farm': 'Create New Farm',
      'Name is required': 'Name is required',
      'Tap to view details': 'Tap to view details',
      'Save Changes': 'Save Changes',
      'Barangay Details': 'Barangay Details',
      'Farms List': 'Farms List',
      'Yield Data': ' Yield Data',
      'Farm Owner': 'Farm Owner',
      'Associations': 'Associations',
      'Total Farms': 'Total Farms',
      'Total Farmers': ' Total Farmers',
      'Avg Farm Size': 'Avg Farm Size',
      'Annual Yield': 'Annual Yield',
      'Area Harvested': 'Area Harvested',
      'Annual Production': ' Annual Production',
      'Total Users': 'Total Users',
      'New Users': 'New Users',
      'Roles': 'Roles',
      'Inactive': 'Inactive',
      'Total Members': 'Total Members',
      'Active': 'Active',
      'Active Associations': 'Active Associations',
      'Total Associations': 'Total Associations',
      'Farmers': 'Farmers',
      'Total Production': 'Total Production',
      'Total Area': 'Total Area',
      'Unique Owners': 'Unique Owners',
      'Avg. Yield': 'Avg. Yield',
      'Growth %': 'Growth %',
      'Annual Growth': 'Annual Growth',
      'Reports': 'Reports',
      'No Report Generated': 'No Report Generated',
      'Configure your filters above and click "Generate Report" to create your first report.':
          'Configure your filters above and click "Generate Report" to create your first report.',
      'Get Started': 'Get Started',
      'No Data Found': 'No Data Found',
      'No Record':
          'No records match your current filter criteria. Try adjusting your filters or selecting a different date range.',
      'Reset Filters': 'Reset Filters',
      'Try Again': 'Try Again',
      'Generating report...': 'Generating report...',
      'Search...': 'Search...',
      'Report Filters': 'Report Filters',
      'Report Type': 'Report Type',
      'Generate Report': 'Generate Report',
      'Select Columns': 'Select Columns',
      'Crop Suitability': 'Crop Suitability',
      'Crop Recommendation': 'Crop Recommendation',
      'View Requirements': 'View Requirements',
      'RECOMMENDED': 'RECOMMENDED',
      'Alternative Options': 'Alternative Options',
      'View Details': 'View Details',
      'Model Consensus': 'Model Consensus',
      'Analysis Summary': 'Analysis Summary',
      'Crops Analyzed': 'Crops Analyzed',
      'Confidence Threshold': 'Confidence Threshold',
      'Low Confidence': 'Low Confidence',
      'Crop Requirements': 'Crop Requirements',
      'SUITABLE': 'SUITABLE',
      'NOT_SUITABLE': 'NOT_SUITABLE',
      'Confidence Level': 'Confidence Level',
      'AI Models Used': 'AI Models Used',
      'Parameter Analysis': 'Parameter Analysis',
      'parameters optimal': 'parameters optimal',
      'Current: ': 'Current: ',
      'Improvement Suggestions': ' Improvement Suggestions',
      'parameters need attention': 'parameters need attention',
      'disclaimer_ai':
          'AI suggestions should be verified with local agricultural experts',
      'Needs Attention': 'Needs Attention',
      'Get AI Suggestions': 'Get AI Suggestions',
      'Check Another Configuration': 'Check Another Configuration',
      'Select All': 'Select All',
      'Clear All': 'Clear All',
      'Apply Filters': 'Apply Filters',
      'No data available': 'No data available',
      'Land Area': 'Land Area',
      'Size:': 'Size:',
      'Plots:': 'Plots:',
      'Total Products': 'Total Products',
      'Varieties:': 'Varieties:'
    },
    'fil': {
      'Varieties:': 'Iba t Ibang Uri:',
      'Total Products': 'Kabuuang Mga Produkto',
      'Plots:': 'Mga Plots:',
      'Size:': 'Laki:',
      'Land Area': 'Lupang Sakahan',
      'No data available': 'Walang available na data',
      'Apply Filters': 'I-apply ang Mga Filter',
      'Clear All': 'I-clear Lahat',
      'Select All': 'Piliin Lahat',
      'Check Another Configuration': 'Suriin ang Ibang Konfigurasyon',
      'Get AI Suggestions': 'Kumuha ng Mga Mungkahi ng AI',
      'Needs Attention': 'Nangangailangan ng Pansin',
      'disclaimer_ai':
          'Ang mga mungkahi ng AI ay dapat beripikahin sa mga lokal na eksperto sa agrikultura',
      'parameters need attention': 'mga parameter na nangangailangan ng pansin',
      'Improvement Suggestions': ' Mga Mungkahi sa Pagpapabuti',
      'Current: ': 'Kasalukuyan: ',
      'parameters optimal': 'mga parameter na optimal',
      'Parameter Analysis': 'Pagsusuri ng Parameter',
      'AI Models Used': 'Mga Ginamit na Modelo ng AI',
      'Confidence Level': 'Antas ng Kumpiyansa',
      'NOT_SUITABLE': 'HINDI ANGKOP',
      'SUITABLE': 'ANGKOP',
      'Crop Requirements': 'Mga Kinakailangan sa Pananim',
      'Low Confidence': 'Mababang Kumpiyansa',
      'Confidence Threshold': 'Confidence Threshold',
      'Crops Analyzed': 'Mga Pananim na Nasuri',
      'Analysis Summary': 'Buod ng Pagsusuri',
      'Model Consensus': 'Konsensus ng Modelo',
      'View Details': 'Tingnan ang Mga Detalye',
      'Alternative Options': 'Mga Alternatibong Opsyon',
      'RECOMMENDED': 'INIREREKOMENDA',
      'View Requirements': 'Tingnan ang Mga Kinakailangan',
      'Crop Recommendation': 'Rekomendasyon na Pananim',
      'Crop Suitability': 'Angkop ng Pananim',
      'Select Columns': 'Pumili ng Mga Column',
      'Generate Report': 'Gumawa ng Ulat',
      'Report Type': 'Uri ng Ulat',
      'Report Filters': 'Mga Filter ng Ulat',
      'Search...': 'Maghanap...',
      'Generating report...': 'Gumagawa ng ulat...',
      'Try Again': 'Subukang Muli',
      'Reset Filters': 'I-reset ang mga Filter',
      'No Record':
          'Walang rekord na tumutugma sa iyong kasalukuyang mga pamantayan sa filter. Subukang ayusin ang iyong mga filter o pumili ng ibang saklaw ng petsa.',
      'No Data Found': 'Walang Nahanap na Data',
      'Get Started': 'Magsimula',
      'Configure your filters above and click "Generate Report" to create your first report.':
          'I-configure ang iyong mga filter sa itaas at i-click ang "Generate Report" upang lumikha ng iyong unang ulat.',
      'No Report Generated': 'Walang Nabuong Ulat',
      'Reports': 'Ulat',
      'Annual Growth': 'Taunang Paglago',
      'Growth %': 'Paglago %',
      'Avg. Yield': 'Karaniwang Ani',
      'Unique Owners': 'Natatanging mga May-ari',
      'Total Area': 'Kabuuang Lupa',
      'Total Production': 'Kabuuang Produksyon',
      'Farmers': 'Mga Magsasaka',
      'Total Associations': 'Kabuuang mga Asosasyon',
      'Active Associations': 'Aktibong Mga Asosasyon',
      'Active': 'Aktibo',
      'Total Members': 'Kabuuang mga Miyembro',
      'Inactive': 'Hindi Aktibo',
      'Roles': 'Mga Role',
      'New Users': 'Mga Bagong User',
      'Total Users': 'Kabuuang mga User',
      'Annual Production': 'Taunang Produksyon',
      'Area Harvested': 'Lupang Inani',
      'Annual Yield': 'Taunang Ani',
      'Avg Farm Size': 'Karaniwang Laki ng Sakahan',
      'Total Farms': 'Kabuuang mga Sakahan',
      'Total Farmers': 'Kabuuang mga Magsasaka',
      'Associations': ' Mga Asosasyon',
      'Farm Owner': ' May-ari ng Sakahan',
      'Yield Data': ' Datos ng Ani',
      'Farms List': 'Listahan ng mga Sakahan',
      'Barangay Details': 'Mga Detalye ng Barangay',
      'Save Changes': 'I-save ang mga Pagbabago',
      'Tap to view details': 'I-tap upang makita ang mga detalye',
      'Name is required': 'Kinakailangan ang Pangalan',
      'Create New Farm': 'Gumawa ng Bagong Sakahan',
      'Create Farm': 'Gumawa ng Sakahan',
      'products & Distribution': 'Mga Produkto at Distribusyon',
      'Recent Records': 'Mga Kamakailang Rekord',
      'Farm Profile': 'Profile ng Sakahan',
      'Adding...': 'Dinadagdag...',
      'Add Record': 'Magdagdag ng Rekord',
      'Farms': 'Mga Sakahan',
      'Product Name': 'Pangalan ng Produkto',
      'Product Sector': 'Sektor ng Produkto',
      'Delete': 'Burahin',
      'Cancel': 'Kanselahin',
      'Are you sure you want to delete this record?':
          'Sigurado ka bang gusto mong tanggalin ang rekord na ito?',
      'Delete Yield': 'Tanggalin ang Ani',
      'Notes': 'Mga Tala',
      'Additional Information': 'Karagdagang Impormasyon',
      'Documentation': 'Dokumentasyon',
      'Value in (Php)': 'Halaga sa (Php)',
      'Harvest Date': 'Petsa ng Pag-aani',
      'Yield Amount': 'Dami ng Ani',
      'Yield Information': 'Impormasyon sa Ani',
      'Area harvested (Ha)': 'Lupang inani (Ha)',
      'Farm Name': 'Pangalan ng Sakahan',
      'Farm Information': 'Impormasyon sa Sakahan',
      "Location": "Lokasyon",
      "Farmer Name": "Pangalan ng Magsasaka",
      "Product Information": "Impormasyon ng Produkto",
      'Record Details': 'Mga Detalye ng Rekord',
      'Edit Product': 'I-edit ang Produkto',
      'Edit Profile': 'I-edit ang Profile',
      'Save Profile': 'I-save ang Profile',
      'Yields': 'Ani',
      'Sectors': 'Mga Sektor',
      'language': 'Wika',
      'save': 'I-save',
      'welcome': 'Maligayang pagdating',
      'Change Password': 'Palitan ang Password',
      'Current Password': 'Kasalukuyang Password',
      'New Password': 'Bagong Password',
      'Confirm New Password': 'Kumpirmahin ang Bagong Password',
      'MTG-text':
          'Mag-migrate sa Google authentication para sa mas madaling pag-sign-in',
      'Disconnect Google': 'I-disconnect ang Google',
      'Migrate to Google': 'I-migrate sa Google',
      'Settings': 'Mga Setting',
      ''
              'Click the first point to close shape and save it':
          'I-click ang unang punto upang isara ang hugis at i-save ito',
      'Enter Environmental Parameters':
          'Ilagay ang mga Parameter ng Kapaligiran',
      'Predict': 'Hulaan',
      'Select Model': 'Pumili ng Modelo',
      'Select Crop': 'Pumili ng Pananim',
      'Check Suitability': 'Suriin ang Angkop',
    },
  };

  static String t(String key, {String languageCode = 'en'}) {
    return _translations[languageCode]?[key] ??
        _translations['en']![key] ??
        key;
  }

  static const supportedLocales = [
    Locale('en'),
    Locale('fil'),
  ];
}
